### ISSUE TITLE
example/example_catalog.txt is missing?

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/Pangloss#37]
@tcollett, is the repo missing a file? I am running the example, which runs fine (in the wl branch, using astropy tables!) until line 239 of `Drill.py`

> Drill: All 1000 calibration lightcones made.
> Drill: Reading in observed catalog: /Users/pjm/work/stronglensing/H0/lightcones/Pangloss/example/example_catalog.txt
> Traceback (most recent call last):
>   File "/Users/pjm/work/stronglensing/H0/lightcones/Pangloss/Drill.py", line 239, in <module>
>     Drill(sys.argv[1:])
>   File "/Users/pjm/work/stronglensing/H0/lightcones/Pangloss/Drill.py", line 201, in Drill
>     table = pangloss.readCatalog(obscat,experiment)
>   File "/Users/pjm/work/stronglensing/H0/lightcones/Pangloss/pangloss/io.py", line 59, in readCatalog
>     raise IOError("Cannot open %s\n" % filename)
> IOError: Cannot open /Users/pjm/work/stronglensing/H0/lightcones/Pangloss/example/example_catalog.txt

**Comment by tcollett** [comment]
Did you already do

cd calib
Fetch.csh

?

**Comment by drphilmarshall** [comment]
Yes, I ran `Fetch.csh` and it completed fine. I see that it contains the following line:

```
set targets = (\
    Millennium/kappa_example.fits \
    Millennium/catalog_example.txt \
    SHMR/HaloMassRedshiftCatalog.pickle )
```

But the `example.config` file wants

```
ObservedCatalog: $PANGLOSS_DIR/example/example_catalog.txt
```

I guess the right thing to do is to extend `Fetch.csh` to grab this file and put it in the example folder? If it's not too big you could also just check it in to the git repo.

**Comment by tcollett** [comment]
So you've got the data, but it's in the wrong folder?

**Comment by drphilmarshall** [comment]
OK - I'll try using Millennium/catalog_example.txt as
example/example_catalog.txt,
and if it works I'll edit the example.config. Thanks Tom!

**Comment by tcollett** [comment]
No worries. Did it work?

**Comment by drphilmarshall** [comment]
Almost: `Drill.py` gives this message:

> Drill: Taking instructions from example.config
> Drill: Making 1000 calibration lightcones in 1 sky patches:
> Drill: Reading in calibration catalog from 
> /Users/pjm/work/stronglensing/H0/lightcones/Pangloss/calib/Millennium/catalog_example.txt...
> 
> ...
> Drill: Reading in observed catalog: 
> /Users/pjm/work/stronglensing/H0/lightcones/Pangloss/example/example_catalog.txt
> Lightcone: WARNING: no galaxies here!
> Drill: Observed lightcone pickled to
> /Users/pjm/work/stronglensing/H0/lightcones/Pangloss/example/example_catalog_lightcone.pickle

So I'm thinking that `calib/Millennium/catalog_example.txt` is not the right catalog to be used as an example `ObservedCatalog`... I'll put the code that I'm running in a separate branch for you to play around with - watch out though, we've switched to astropy now so you'll need to have that installed.

**Comment by drphilmarshall** [comment]
Actually, scratch that - too many files have been changed! If you want to try reproducing my result, please checkout the `wl` branch and edit there. Thanks @tcollett !
